version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - WanzenBug
    groups:
      ci:
        patterns:
          - "*" # Include all github-actions update in one PR
