{{- if (include "linstor-cluster.createApiTLSCert" .) }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "linstor-cluster.fullname" $ }}-api-tls
  labels:
    {{- include "linstor-cluster.labels" $ | nindent 4 }}
spec:
  commonName: {{ include "linstor-cluster.fullname" $ }}-api-tls
  secretName: {{ include "linstor-cluster.fullname" $ }}-api-tls
  duration: 87600h0m0s # 10 years
  isCA: true
  usages:
    - signing
    - key encipherment
    - cert sign
  issuerRef:
    name: {{ include "linstor-cluster.fullname" $ }}-ca-bootstrapper
    kind: Issuer
{{- end }}
{{- if (include "linstor-cluster.createInternalTLSCert" .) }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "linstor-cluster.fullname" $ }}-internal-tls
  labels:
    {{- include "linstor-cluster.labels" $ | nindent 4 }}
spec:
  commonName: {{ include "linstor-cluster.fullname" $ }}-internal-tls
  secretName: {{ include "linstor-cluster.fullname" $ }}-internal-tls
  duration: 87600h0m0s # 10 years
  isCA: true
  usages:
    - signing
    - key encipherment
    - cert sign
  issuerRef:
    name: {{ include "linstor-cluster.fullname" $ }}-ca-bootstrapper
    kind: Issuer
{{- end }}
