{{- if or (include "linstor-cluster.createApiTLSCert" .) (include "linstor-cluster.createInternalTLSCert" .) }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "linstor-cluster.fullname" $ }}-ca-bootstrapper
  labels:
    {{- include "linstor-cluster.labels" . | nindent 4 }}
spec:
  selfSigned: { }
{{- end }}
{{- if (include "linstor-cluster.createInternalTLSCert" .) }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "linstor-cluster.fullname" $ }}-internal-tls
  labels:
    {{- include "linstor-cluster.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "linstor-cluster.fullname" $ }}-internal-tls
{{- end }}
{{- if (include "linstor-cluster.createApiTLSCert" .) }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "linstor-cluster.fullname" $ }}-api-tls
  labels:
    {{- include "linstor-cluster.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "linstor-cluster.fullname" $ }}-api-tls
{{- end }}
