{{- if .Values.linstorPassphrase }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linstor-cluster.linstorPassphraseSecret" . }}
  labels:
    {{- include "linstor-cluster.labels" . | nindent 4 }}
stringData:
  MASTER_PASSPHRASE: {{ .Values.linstorPassphrase | quote }}
{{- end }}
