{{- if (include "linstor-cluster.createPassPhraseSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linstor-cluster.fullname" $ }}-passphrase
  labels:
    {{- include "linstor-cluster.labels" . | nindent 4 }}
stringData:
  MASTER_PASSPHRASE: {{ .Values.linstorCluster.linstorPassphraseSecret.masterPassPhrase }}
{{- end }}
