{{- range .Values.storageClasses }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
{{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "linstor-cluster.labels" $ | nindent 4 }}
{{- if .labels }}
    {{- toYaml .labels | nindent 4 }}
{{- end }}
provisioner: {{ .provisioner | default "linstor.csi.linbit.com" }}
reclaimPolicy: {{ .reclaimPolicy | default "Delete" }}
volumeBindingMode: {{ .volumeBindingMode | default "WaitForFirstConsumer" }}
allowVolumeExpansion: {{ .allowVolumeExpansion | default "true" }}
{{- if .parameters }}
parameters:
  {{- toYaml .parameters | nindent 2 }}
{{- end }}
{{- end }}
