{{ if .Values.monitoring.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "linstor-affinity-controller.fullname" . }}
  labels:
    {{- include "linstor-affinity-controller.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      {{- include "linstor-affinity-controller.selectorLabels" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linstor-affinity-controller.fullname" . }}
  labels:
    {{- include "linstor-affinity-controller.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "linstor-affinity-controller.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: 8001
    targetPort: metrics
    protocol: TCP
{{ end }}
