{{- range .Values.volumeSnapshotClasses }}
---
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: {{ .name }}
{{- with .annotations }}
  annotations: {{- . | toYaml | trim | nindent 4 }}
{{- end }}
  labels:
  {{- include "snapshot-controller.labels" $ | nindent 4 }}
driver: {{ .driver }}
deletionPolicy: {{ .deletionPolicy }}
{{- with .parameters }}
parameters: {{- . | toYaml | trim | nindent 2 }}
{{- end }}
{{- end }}